spring:
  application:
    name: trainer-stats-service

server:
  port: 8081

eureka:
  client:
    service-url:
      #      defaultZone: ${EUREKA_DEFAULT_ZONE}
      defaultZone: http://localhost:8094/eureka