spring:
  application:
    name: trainer-stats-service

service:
  main: main-service

server:
  port: 8081

token:
  key: ${TOKEN_KEY:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8094/eureka}