service:
  trainer-stats-service: trainer-stats-service

resilience4j:
  circuitbreaker:
    instances:
      TrainerStatsServiceCircuitBreaker:
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 5
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s