spring:
  application:
    name: main-service

logging:
  file:
    path: logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} transactionId=[%X{transactionId}]
            - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} transactionId=[%X{transactionId}]
            - %msg%n'
server:
  port: 8080

token:
  key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

eureka:
  client:
    service-url:
      #      defaultZone: ${EUREKA_DEFAULT_ZONE}
      defaultZone: http://localhost:8094/eureka

service:
  trainer-stats-service: trainer-stats-service

resilience4j:
  circuitbreaker:
    instances:
      TrainerStatsServiceCircuitBreaker:
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 5
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s