logging:
  file:
    path: logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} transactionId=[%X{transactionId}]
            - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} transactionId=[%X{transactionId}]
            - %msg%n'
server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url:      ${DB_URL:jdbc:mysql://localhost:3307/gym}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}