management:
  endpoint:
    health:
      show-components: never
      show-details: never

spring:
  datasource:
    driver-class-name: ${PROD_DB_DRIVER_CLASS_NAME}
    url:      ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: false
