management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints.web.exposure.include: 'prometheus, health'
  prometheus:
    metrics:
      export:
        enabled: true
